// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekMOoSdlwEG0_3McPHWAPj6WA8BK3KrY',
    appId: '1:692512687197:web:7088562a43c274c1ab79b4',
    messagingSenderId: '692512687197',
    projectId: 'lim-d8b7d',
    authDomain: 'lim-d8b7d.firebaseapp.com',
    storageBucket: 'lim-d8b7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAblGa4VvMzqMPLKqGFKBwqrC1f6A90izk',
    appId: '1:692512687197:android:d2fba4533eb91accab79b4',
    messagingSenderId: '692512687197',
    projectId: 'lim-d8b7d',
    storageBucket: 'lim-d8b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCToCFGS8hjrUN1HZF_sPhpUcbMW7f0PkI',
    appId: '1:692512687197:ios:667bbce5b4d794bcab79b4',
    messagingSenderId: '692512687197',
    projectId: 'lim-d8b7d',
    storageBucket: 'lim-d8b7d.appspot.com',
    iosBundleId: 'com.example.leokris88lim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCToCFGS8hjrUN1HZF_sPhpUcbMW7f0PkI',
    appId: '1:692512687197:ios:4da9443b1e6de902ab79b4',
    messagingSenderId: '692512687197',
    projectId: 'lim-d8b7d',
    storageBucket: 'lim-d8b7d.appspot.com',
    iosBundleId: 'com.example.leokris88lim.RunnerTests',
  );
}
